kumuluzee:
  name: songs
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://192.168.99.100:8081
    http:
      port: 8081
  discovery:
      etcd:
        hosts: http://192.168.99.100:2379
      ttl: 30
      ping-interval: 5

  datasources:
      - jndi-name: jdbc/SongsDS
        connection-url: jdbc:postgresql://192.168.99.100:5433/songs
        username: postgres
        password: postgres
        max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/SongsDS
  metrics:
      web-instrumentation:
        - name: metricsEndpoint
          url-pattern: /metrics/*
        - name: customersEndpoint
          url-pattern: /v1/songs/*

  logs:
        config-file: '<?xml version="1.0" encoding="UTF-8"?>
                       <Configuration name="songs">
                           <Appenders>
                               <Console name="console" target="SYSTEM_OUT">
                                   <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                               </Console>
                               <Socket name="logstash" host="45b3a890-bc4a-4fa6-b1b0-74ff1f25736c-ls.logit.io" port="14448" protocol="tcp">
                                   <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                               </Socket>
                           </Appenders>
                           <Loggers>
                               <!-- Default logger -->
                               <Root level="all">
                                   <AppenderRef ref="console" level="info"/>
                                   <AppenderRef ref="logstash" level="trace"/>
                               </Root>
                           </Loggers>
                       </Configuration>'