apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-songs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-songs
    spec:
      containers:
        - image: postgres
          name: postgres-songs
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: songs
          ports:
          - containerPort: 5433
            protocol: TCP