apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-songs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-songs
    spec:
      containers:
        - image: centos/postgresql-94-centos7
          name: postgres-songs
          env:
            - name: POSTGRESQL_USER
              value: userdb
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: songs
          ports:
          - containerPort: 5432
            protocol: TCP