apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: songs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: songs
    spec:
      containers:
      - image: cleptes/songs:0.01
        name: songs
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-songs:5433/songs
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: postgres
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
        ports:
        - containerPort: 8081
          #name: server
          #protocol: TCP