apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: songs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: songs
    spec:
      containers:
      - image: cleptes/songs
        name: songs
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-songs:5433/songs
          - name: KUMULUZEE_DATASOURCES0_USERNAME
            value: userdb
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.16.117:32280
          - name: KUMULUZEE_VERSION
            value: 1.0.1
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP